
spring:
  datasource:
    url: jdbc:h2:mem:cryptodb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

